project:
  type: website
  output-dir: docs

website:
  title: "Sarah Smith-Tripp"
  favicon: assets/Phd_Logo.png
  site-url: https://sarahsmithtripp.github.io
  description: "Personal Website for Sarah Smith-Tripp"
  navbar:
    title: "Sarah Smith-Tripp"
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: "Research"
      - about.qmd
      - posts.qmd
      - currentprojects.qmd
      - href: blogroll.qmd
        text: "Blog Roll"
      - icon: rss
        href: posts.xml
  google-analytics: "G-WR4VFC0MC2"
  cookie-consent: true
  twitter-card:
    creator: "@smithtripp21"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

